# ansible 2.2

---
- hosts: "app"
  sudo: "yes"
  remote_user: "vagrant"

  tasks:
    - name: "Update"
      apt: update_cache=yes

    - name: Instalar Python
      apt: name=python state=present

    - name: Instalar Pip
      apt: name=python-pip state=present

    - name: Instalar Git
      apt: name=git state=present

    - name: Descargar repositorio de la aplicación
      git: repo=https://github.com/terceranexus6/copylazyjacker dest=/home/vagrant/copylazyjacker
